const {
  createRequest,
  makePhotoURL,
  sendMessage,
  sendPhotoMessage,
  processModerationRequest,
  isUserCanCreateRequest,
  getFileLink,
  sendPhotoStream,
  getNewPhotoId,
  createRequestAndModerate,
} = require('./logic');

const {
  registerUser,
  changeUserActivity,
  getUserId,
  getUserRequests,
  getRequestsInRegLocation,
  getRequestsInArea,
  deleteRequest,
  getUserActivity,
  getUsersInRequestRadius,
  getBadRequestCount,
  getTimeOfLastRequestFromUser,
  setBadRequestCountZero,
  getUserName,
  setUserName,
  getPlatformIdFromRequest,
  getPlatformTypeRequestId,
  getUserStep,
  setUserStep,
  getUserLocation,
  changeRequestActiveStatus,
} = require('./requestDB');

module.exports = {
  createRequest,
  makePhotoURL,
  sendMessage,
  sendPhotoMessage,
  processModerationRequest,
  isUserCanCreateRequest,
  getFileLink,
  sendPhotoStream,
  getNewPhotoId,
  createRequestAndModerate,
  registerUser,
  changeUserActivity,
  getUserId,
  getUserRequests,
  getRequestsInRegLocation,
  getRequestsInArea,
  deleteRequest,
  getUserActivity,
  getUsersInRequestRadius,
  getBadRequestCount,
  getTimeOfLastRequestFromUser,
  setBadRequestCountZero,
  getUserName,
  setUserName,
  getPlatformIdFromRequest,
  getPlatformTypeRequestId,
  getUserStep,
  setUserStep,
  getUserLocation,
  changeRequestActiveStatus,
};
