module.exports = {
  TRUE: 'true',
  FALSE: 'false',
  BUTTONS: {
    NEW_LOCATION: 'newLocation',
    REGISTRATE_LOCATION: 'registrateLocation',
  },
  CHANGE_USER_ACTIVITY: /changeUserActivity/,
  CLOSE_OWN_REQUEST: /closeOwnRequest/,
  CLOSE_REQUEST: /closeRequest/,
  CONTROL_PANEL: /controlPanel/,
  CREATE_REQUEST: /createRequest/,
  FIND_USERS_REQUESTS: /findUsersRequests/,
  LOCATION_CHOISE: /locationChoise/,
  REGISTRATE_USER: /registrateUser/,
  REQUEST_MENU: /requestMenu/,
  REQUEST_TYPE: /requestType/,
  RETURN_MAIN_MENU: /returnMainMenu/,
  UPDATE_LOCATION: /updateLocation/,
};
