require('dotenv').config();

module.exports = {
    TOKEN: process.env.TOKEN,
    db: {
        user: process.env.PGUSER,
        host: process.env.PGHOST,
        database: process.env.PGDATABASE,
        password: process.env.PGPASSWORD,
        port: process.env.PGPORT,
    },
    MAIN_MENU_BUTTON_REGISTRATION: 'Зареєструватися або оновити свої координати',
    MAIN_MENU_BUTTON_REQUEST: 'Подати заявку на пошук',
    MAIN_MENU_BUTTON_SAMPLE: 'Вибірка улюбленців яких шукають або знайшли',
    REGISTRATION_MENU_BUTTON_REGISTRATION: 'Зареєструватися',
    REGISTRATION_MENU_BUTTON_CHANGE_LOCATION: 'Змінити свою локацію',
    REGISTRATION_MENU_BUTTON_DELETE_USER: 'Видалитися із системи',
    REGISTRATION_MESSAGE: 'Відправте Вашу локацію ',
    REGISTRATION_ERROR: 'Локація була введена невірно, спробуйте знову',
    REGISTRATION_ENTER: 'Дякую, Ваш запит прийнято',
    APPLY_MENU_SEARCH: 'Я загубив улюбленця',
    APPLY_MENU_FIND: 'Я знайшов улюбленця',
    APPLY_MENU_DELETE: 'Видалити свою заявку',
    DELETE_USER_QUESTION: 'Ви впевнені що бажаєте видалитися? (відправте повідомлення так чи ні)',
    DELETE_USER_TRUE: 'Ваш запит на видалення прийнято',
    DELETE_USER_FALSE: 'Відміна видалення',
    WELCOME_MESSAGE: 'Привіт, для початку роботи зі мною зареєструйтесь в системі',
    REGISTRATION_MENU_MESSAGE: 'Ви в меню реєстрації, виберіть один із пунктів',
    REQUEST_MENU_MESSAGE: 'Ви в меню подачі заявки на пошук,  виберіть один із пунктів',
    CHANGE_LOCATION_SCENE_MESSAGE: 'Введіть ваші нові GPS координати',
    DELETE_PET_SCENE_MESSAGE: 'Список ваших заявок які ви можете видалити',
    SEARCH_PET_SCENE_PHOTO_MESSAGE: 'Завантажте фотографію загубленого домашньго улюбленця',
    SEARCH_PET_SCENE_LOCATION_MESSAGE: 'Завантажте місце (локацію) де улюбленець загубився',
    SEARCH_PET_SCENE_DESCRIPTION_MESSAGE: 'Введіть невеликий опис улюбленця одним повідомленням',
    SEARCH_PET_SCENE_ERROR: 'Помилка введення, спробуйте знову',
    FIND_PET_SCENE_PHOTO_MESSAGE: 'Завантажте фотографію знайденої тваринки',
    FIND_PET_SCENE_LOCATION_MESSAGE: 'Завантажте місце де улюбленець був знайдений',
    FIND_PET_SCENE_DESCRIPTION_MESSAGE: 'Введіть невеликий опис улюбленця одним повідомленням',
    // DELETE_PET_SCENE_QUESTION: 'Улюбленець знайшовся? (напишіть так чи ні)',
    GET_INFO_SCENE_LENGTH_MESSAGE: `В якому радіусі від ваших координат відібрати повідомлення пошуку?
    Введіть числове значення в метрах (приклад 2км = 2000)`,
    GET_INFO_SCENE_DAYS_MESSAGE: `На скільки старі повідомлення ви хочете відібрати?
    Введіть числове значення в днях (приклад пошукові повідомлення які були подані протягом останніх 2-х місяців - 60)`,
};
