version: "3.7"
services:
  db:
    image: postgres:11-alpine
    volumes:
      - ./.base/data:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./.env.db
    ports:
      - 5431:5432
  web:
    image: wimp
    depends_on:
      - db
    restart: always
    ports:
      - 3030:3000
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
